env:
  default:
    apps:
      your-app:
        host: http://localhost
        port: 8080
        type: rest
        enabled: true
      your-another-app:
        host: http://localhost
        port: 5051
        type: grpc
        enabled: false
    test-data-dir: testdata
    mock:
      host: http://localhost
      port: 8080
      enabled: true
      stubs-path: src/test/resources/stubs